### ISSUE TITLE
Feature request: maximum of a property along the past merger history for all haloes in a snapshot

### ISSUE THREAD

**Issue by TobiBu** [pynbody/tangos#67]
Hi,

I like to calculate the maximum of a property, say V_max or M_vir, along the past merger history for all haloes in a snapshot. Currently tangos provides this feature for a single halo using the syntax 
`Vpeak = halo.calculate("Vmax", "max")`
but not for all haloes in a snapshot.

**Comment by apontzen** [comment]
I agree this could be useful feature. It should be possible to implement efficiently as a new `builtin_function`, using the existing `MultiSourceMultiHopStrategy` class to perform the database search. 

I am surprised that `halo.calculate("Vmax", "max")` does what you want for a single halo though. Wouldn't it currently need to be something more like `numpy.max(halo.calculate_for_progenitors("Vmax"))`?

**Comment by TobiBu** [comment]
Hi,

indeed, I messed up when copying from my ipython history.

Thanks for pointing me towards a strategy to implement such a feature. I will take a look.

**Comment by apontzen** [comment]
- I'm not sure why you'd need an unused parameter; e.g. `earliest` and `latest` take only the `source_halos` parameter so clearly it is possible to make this work. What exactly fails when you don't have this parameter? Have you accidentally applied `set_input_options` to a non-existent input perhaps?
- It's a restriction of the mini-language that you can indeed only return a scalar so you will need to take the maximum before returning the array (unless you want to expand the language itself!)
 - In terms of your implementation, I'm guessing you'll find this relatively slow. In fact doing this probably has O(n^2) complexity where n is the number of timesteps. 
 - It'd be faster to get the entire history of every halo in one query, rather than re-query for every timestep. One possible direction to try would be using `MultiSourceMultiHopStrategy` with `directed=backwards`, but no `target` -- that should give you every progenitor for every halo in a single query.

**Comment by TobiBu** [comment]
thanks for the help.

I was indeed setting the input parameter.

I tried out using `MultiSourceMultiHopStrategy´as suggested by you but I could not get all the progenitors for all halos, I always get the the result for the timestep I am working on. 
I guess we can talk next week in one of the coffee breaks.

**Comment by apontzen** [comment]
Yes, good plan

**Comment by apontzen** [comment]
I tried implementing this in branch `progenitor-search` (PR #69). Please give it a go and let me know what you think.

The new syntax to achieve what you want would be something like `timestep.calculate_all("find_progenitor(Vmax,'max')")`. This will return the actual progenitor concerned. So if you want just the values it would instead be `timestep.calculate_all("find_progenitor(Vmax,'max')").Vmax`. I think you will find this is faster than doing it manually for each halo, but let me know!

**Comment by TobiBu** [comment]
It works well and fast! Thanks.

However, I get the following issue when typing your second suggestion
`timestep.calculate_all("find_progenitor(Vmax,'max')").Vmax`

`AttributeError: 'list' object has no attribute 'Vmax'`

**Comment by apontzen** [comment]
Oops, sorry, that should have been `timestep.calculate_all("find_progenitor(Vmax,'max').Vmax")`.

**Comment by TobiBu** [comment]
works perfectly, thanks

**Comment by apontzen** [comment]
Merged into master
